[package]
name = "simple_eval"
version = "0.1.0"
authors = ["Tatounee <oettam32@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"
lazy_static = "1.4.0"